# frozen_string_literal: true

source "https://rubygems.org"

gem 'allure-cucumber', '2.13', '2.13.9'
gem 'cucumber', '6.1'
gem 'capybara', '3.33'
gem 'rspec', '3.10'
gem 'faker', '2.14'
gem 'mongo', '2.13.1'
gem 'selenium-webdriver', '3.142', '3.142.7'